# Generated by Django 5.2.4 on 2025-07-17 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_comment_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_at',
            new_name='posted_at',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='text',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
