# Generated by Django 5.2.4 on 2025-07-19 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_rename_created_at_comment_posted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
